---
title: "Get weather data"
output: html_document
date: "2024-06-05"
---
```{r}
library(DT)
library(fmi2)
library(ggplot2)
library(knitr)
library(leaflet)
library(sf)
library(skimr)
```
```{r}
station_data <- fmi2::fmi_stations() 

station_data %>% 
  DT::datatable()

```



```{r}
list=c(100909,100919,100928,100821,100908,100924,100945,101464,100946,100965,100969,100997,100996,101022,101023,101039,101042,101059,101061,101267)
#ststion_options=
# Plot on a map using leaflet
leaflet::leaflet(station_data) %>% 
  leaflet::addTiles() %>%  
  leaflet::addMarkers(~lon, ~lat, popup = ~name, label = ~as.character(fmisid))


```


```{r}
#library("prob")
setwd("/home/milenava/Seals/Grey_seals/Data_for_code")
station_options=station_data[station_data$fmisid %in% list,]

year=seq(from=2003, to=2020, length=18)
k=1
year
C_tot={}

for (y in year){
  if(y!= 2018){
  df=read.csv(paste("HO_",y,".csv", sep=""))
  C_tot[k]=sum(df$Hallit)
  df=df[df$Hallit >10,]
  df=df[c("Luoto", "Hallit", "Havaintopvm", "E", "N")]
  df
  WS={}
  S={}
  T={}
  df$Month=substring(df$Havaintopvm,4,5)
  df$Day=substring(df$Havaintopvm,1,2)
    for ( i in 1:nrow(df)){
    lon=df$E[i]
    lat=df$N[i]
    l_min=10000
    for ( j in 1:nrow(station_options)){
      l=(station_options$lat[j]-lat)^2+(station_options$lon[j]-lon)^2
      if (l<l_min){
        l_min=l
        S[i]=station_options$fmisid[j]
        id=station_options$fmisid[j]
        
        }
    }
   # temp_station <- station_data %>% 
  #  dplyr::filter(fmisid == id)
   # date=paste(y, df$Month[i], df$Day[i], sep="-")
    #temp_data <- obs_weather_daily(starttime = date ,
                                  #   endtime = date,
                                   #  fmisid = id)
    #print(id)
#    wide_data <- temp_data %>% 
 #   tidyr::spread(variable, value) %>% 
  #  sf::st_set_geometry(NULL)
   # T[i]=wide_data$tday
  }
  df$id=S
  #df$T=T
  #WS=WS
  
  df=aggregate(df$Hallit, list(DateHour=df$Havaintopvm, id=df$id), FUN=sum)
  df$max <- ave(seq_len(nrow(df)), df$id,FUN = function(i) df$x[i][which.max(df$x[i])])
  df=df[df$max==df$x,]
  
  
  
  if (k==1){
   df_tot=df
  }
  else{
    df_tot=rbind(df_tot, df)}
  }
  k=k+1 
}
  
df_tot

```
```{r}
id_list=unique(df_tot$id)
m=1
for ( id in id_list){
  station=Stations[Stations$fmisid==id,]$name[1]
  print(station)

  df_w=read.csv(paste(station, "csv", sep="."))
  
  df_tot$Day=as.numeric(substring(df_tot$DateHour, 1,2))
  df_tot$Month=as.numeric(substring(df_tot$DateHour, 4,5))
  df_tot$Year=as.numeric(substring(df_tot$DateHour, 7,10))
  df_tot$Hour=as.numeric(substring(df_tot$DateHour, 12,13))
  df_tot$Date=paste(df_tot$Day,df_tot$Month, df_tot$Year,df_tot$Hour, sep="/")
  df_w$Hour=as.numeric(substring(df_w$Time..Local.time.,1,2))
  df_w$Date=paste(df_w$Day,df_w$Month, df_w$Year,df_w$Hour ,sep="/")
  df_w=df_w[df_w$Date %in% unique(df_tot$Date),]
  df_w$id=id
  if(m==1)
  {
    df_w_tot=df_w
  }
  else{df_w_tot=rbind(df_w_tot, df_w)}
  m=m+1
}
df_w_tot

df_tot
df_w
unique(df_tot$DateHour)
df_w=read.csv(paste(station, "csv", sep="."))
df_fin=merge(df_tot, df_w_tot, by=c("id", "Date"))

df_fin
```

```{r}

df_fin$yearly_sumt=ave(df_fin$x,df_fin$Year.x,FUN = sum)
df_fin$rat=df_fin$max/df_fin$yearly_sum
df_fin$WS=as.numeric(df_fin$Wind.speed..m.s.)


ggplot(df_fin)+geom_line(aes(x=Year.x, y=x, col=id))

ggplot(df_fin)+geom_line(aes(x=Year.x, y=rat, col=id))

ggplot(df_fin)+geom_line(aes(x=Year.x, y=WS, col=id))

df_id=df_fin[df_fin$id==100928,]
df_id
ggplot(df_id)+geom_line(aes(x=Year.x, y=rat))

ggplot(df_id)+geom_line(aes(x=Year.x, y=WS))


plot(df_id$Year.x, df_id$x)

points(df_id$Year.x, df_id$WS, col="red")
plot(df_id$Year.x, -df_id$WS, col="red")

summary(lm(rat~WS, data=df_id))

df_fin
plot(df_fin$Year.x,df_fin$yearly_sumt)
```



```{r}
#ggplot(df_tot)+geom_point(aes(x=E, y=N, col=log(Hallit)))

df_tot[df_tot$N>63,]

station_data

plot(station_data$lon,station_data$lat, xlim=c(19,28), ylim=c(59,61))
points(df_tot$E,df_tot$N,col="red", alpha=0.3)

df_tot
points(station_data$lon,station_data$lat)

station_data
```







## Plot of haul-out sites
```{r}
#library("prob")
setwd("/home/milenava/Seals/Grey_seals/Code+data")
station_options=station_data[station_data$fmisid %in% list,]

year=seq(from=2003, to=2020, length=18)

year
C_tot={}

y=2012
k=1
for (y in year){
  if(y!= 2018){
  df=read.csv(paste("HO_",y,".csv", sep=""))
  df=df[df$Hallit >0,]
  df=df[c("Luoto", "Hallit", "Havaintopvm", "E", "N")]
  df$max <- ave(seq_len(nrow(df)), df$Luoto,FUN = function(i) df$Hallit[i][which.max(df$Hallit[i])])
  df$Year=y
  df=df[df$max==df$Hallit,]
  df2=df
  df2=df2[c("Luoto", "max")]
  colnames(df2) <- c("Luoto", y)
  
  if (k==1){
   df_tot=df
   df_tot2=df2
  }
  else{
    df_tot2=merge(df_tot2, df2, by="Luoto", all=TRUE)
    df_tot=rbind(df_tot, df)}
  }
  k=k+1 
}
  
df_tot2
df_tot2[is.na(df_tot2)] <- 0

df_tot2$Sum=sum(df_tot2[2:21,])
df_tot2[1:21,]
```




# Good ?


```{r}
path<- "/home/milenava/Seals/Grey_seals/Data_for_code/"
station_options=station_data[station_data$fmisid %in% list,]


year=seq(from=2003, to=2023, length=21)
k=1
year
C_tot={}

for (y in year){
  if(y!= 2018){
  df=read.csv(paste(path,"HO_",y,".csv", sep=""))
  C_tot[k]=sum(df$Hallit)
  df=df[c("Luoto", "Hallit", "Havaintopvm", "E", "N")]
  df=df[df$Hallit>0,]
  WS={}
  S={}
  T={}
  df$Month=substring(df$Havaintopvm,4,5)
  df$Day=substring(df$Havaintopvm,1,2)
    for ( i in 1:nrow(df)){
    lon=df$E[i]
    lat=df$N[i]
    l_min=10000
    for ( j in 1:nrow(station_options)){
      l=(station_options$lat[j]-lat)^2+(station_options$lon[j]-lon)^2
      if (l<l_min){
        l_min=l
        S[i]=station_options$fmisid[j]
        id=station_options$fmisid[j]
        
        }
    }
  }
  
  df=aggregate(df$Hallit, list(lon=df$E, lat=df$N), FUN=max)
  df$Year=y
 # print(df)
  if (k==1){
   df_tot=df
  }
  else{
    df_tot=rbind(df_tot, df)}
  }
  k=k+1 
}
  
df_tot

```

```{r}


```


```{r}
library("lattice")
library("ggplot2")
library("sf")
library("sp")

B=st_read(dsn = path, layer = "finland_Finland_Country_Boundary")
df_tot$freq <-ave(df_tot$x,df_tot$Year.x,FUN = function(i) df_tot$x[i]/sum(df_tot$x))
  
  ave(seq_len(nrow(df_tot)), df_tot$Year,FUN = function(i) df_tot$x[i]/sum(df_tot$x))
sum(df_tot$freq)


xmin=19
xmax=23
ymin=59
ymax=64

lon=seq(from=xmin, to=xmax, length=100)
lat=seq(from=ymax, to=ymin, length=100)

for ( y in year){
  grid <- expand.grid(lon=lon, lat=lat)
  grid$GS=0
  df_temp=df_tot[df_tot$Year==y,]
  df_temp$x=df_temp$x/sum(df_temp$x)
  #print(sum(df_temp$x))
  for ( i in 1:nrow(df_temp)){
    j=which.min((grid$lon-df_temp$lon[i])^2+(grid$lat-df_temp$lat[i])^2)
    
    grid[j,3]=grid[j,3]+df_temp$x[i]
  #  print(j)
  }
  grid=na.omit(grid)
  p=ggplot()+geom_raster(data=grid, aes(x=lon, y=lat, fill=GS), interpolate = TRUE)+scale_fill_gradient(,low="white", high="red", name="Grey seal frequency")+geom_sf(data=B, fill=NA)+xlim(c(xmin,xmax))+ylim(c(ymin, ymax)) + labs(x=NULL, y=NULL,title=y)
  plot(p)
  #plot(levelplot(grid$GS ~ lon * lat, data=grid, at=c(1,5,8,10,50,100,500,1000), main=paste("Year", y)))
}

df_temp$x=df_temp$x/sum(df_temp$x)

sum(df_temp$freq)


```





```{r}


A= read_sf(dsn = path, layer = "finland_Finland_Country_Boundary")

Data=st_geometry(B)[[1]]
B
Data
datawizard::MP=A$geometry
dataf.frame(MP)
M=as.matrix(MP)
M
df=read.csv("/home/milenava/Seals/Grey_seals/Data_for_code/Finland_Country_Boundary.csv")
plot(A$geometry)

p(M)
info(MP)
str(MP)
M=st_geometry(A)
M[[1]]
D=M[[1]]
as.list(D)
head(D)
E=st_cast(Data, "POLYGON")
plot(D)
st_
st_union(D)
sp.polygons(Data)



geom_point(data=df_tot,aes(x=lon, y=lat))
  
  geom_raster(data=df, x=lon,y=lat)
grid
sf_pol
str(B)
levelplot(grid$GS ~ lon * lat, data=grid, at=c(1,5,8,10,50,100,500,1000), main=paste("Year", y))+layer()
, aes(x=X, y=Y))
library("terra")

ggplot()+geom_raster(data=grid, aes(x=lon, y=lat, fill=GS))+xlim(c(20,23))

grid

A<- vect(system.file("/home/milenava/Seals/Grey_seals/Data_for_code/finland_Finland_Country_Boundary.shp", package="terra"))
A


```

```{r}
library("lattice")
library("ggplot2")
library("sf")
library("sp")

B=st_read(dsn = path, layer = "finland_Finland_Country_Boundary")
#df_tot$freq <-ave(df_tot$x,df_tot$Year.x,FUN = function(i) df_tot$x[i]/sum(df_tot$x))
  
#   ave(seq_len(nrow(df_tot)), df_tot$Year,FUN = function(i) df_tot$x[i]/sum(df_tot$x))
# sum(df_tot$freq)


xmin=19
xmax=23
ymin=59
ymax=64

lon=seq(from=xmin, to=xmax, length=100)
lat=seq(from=ymax, to=ymin, length=100)

for ( y in year){
  grid <- expand.grid(lon=lon, lat=lat)
  grid$GS=0
  df_temp=df_tot[df_tot$Year==y,]
  df_temp$x=df_temp$x/sum(df_temp$x)
  #print(sum(df_temp$x))
  for ( i in 1:nrow(df_temp)){
    j=which.min((grid$lon-df_temp$lon[i])^2+(grid$lat-df_temp$lat[i])^2)
    
    grid[j,3]=grid[j,3]+df_temp$x[i]
  #  print(j)
  }
  grid=na.omit(grid)
  p=ggplot()+geom_raster(data=grid, aes(x=lon, y=lat, fill=GS), interpolate = TRUE)+scale_fill_gradient(,low="white", high="red", name="Grey seal frequency")+geom_sf(data=B, fill=NA)+xlim(c(xmin,xmax))+ylim(c(ymin, ymax)) + labs(x=NULL, y=NULL,title=y)
  plot(p)
  #plot(levelplot(grid$GS ~ lon * lat, data=grid, at=c(1,5,8,10,50,100,500,1000), main=paste("Year", y)))
}

df_temp$x=df_temp$x/sum(df_temp$x)

sum(df_temp$freq)


```