---
title: "Fish"
output: html_document
date: "2024-06-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

df_GoR=read.csv("/home/milenava/Seals/Grey_seals/Data_for_code/GoR_weight_in_catch_and_stock", sep=" ")
df_GoR=df_GoR[df_GoR$Year>=1996,]

df_GoR[,2:ncol(df_GoR)]=1000*df_GoR[,2:ncol(df_GoR)]
df_GoR
df_BS=read.csv("/home/milenava/Seals/Grey_seals/Data_for_code/Herring_25-29_32_Mean _weight_kg", sep=" ")
df_BS=df_BS[df_BS$Year>=1996,]
df_BS[,2:ncol(df_BS)]=1000*df_BS[,2:ncol(df_BS)]
df_BS
df_BB=read.csv("/home/milenava/Seals/Grey_seals/Data_for_code/Herring_BB_weight_at_Age_in_catches_g", sep="\t")
df_BB=df_BB[df_BB$Year>=1996,]
df_BB


df_BS$X7plus=rowMeans(df_BS[,9:ncol(df_BS)])


df_BB$X9plus=rowMeans(df_BB[,11:ncol(df_BB)])
df_BB$X7plus=rowMeans(df_BB[,9:11])
df_GoR$X7plus=rowMeans(df_GoR[,9:ncol(df_GoR)])

df_sprat=read.csv("/home/milenava/Seals/Grey_seals/Data_for_code/Sprat_mean_weight_at_age_g", sep=" ")
df_sprat=df_sprat[df_sprat$Year>=1996,]

df_sprat$X5plus=rowMeans(df_sprat[,6:ncol(df_sprat)])

df_BS
```
```{r}
library(reshape2)
library(ggplot2)
df_GoR$Area="GoR"
df_BS$Area="BS"
df_BB$Area="BB"
df_BS

df=melt(df_BB, id=c('Year'))
df$value=as.numeric(df$value)
ggplot(df)+geom_line(aes(x=Year, y=value, col=variable))+ylab("Mean weight-at-age (g)")+ggtitle("Mean weight-at-age in Bothnian Bay")


df=melt(df_BS, id=c('Year'))
df$value=as.numeric(df$value)
ggplot(df)+geom_line(aes(x=Year, y=value, col=variable))+ylab("Mean weight-at-age (g)")+ggtitle("Mean weight-at-age in Bothnian Sea")

df=melt(df_GoR, id=c('Year'))
df$value=as.numeric(df$value)
ggplot(df)+geom_line(aes(x=Year, y=value, col=variable))+ylab("Mean weight-at-age (g)")+ggtitle("Mean weight-at-age in Gulf or Riga")
```

```{r}
df_catch=read.csv("/home/milenava/Seals/Grey_seals/Data_for_code/Herring_catch_in_numbers_at_age_ICES_25-29_32.csv")
df_catch= subset(df_catch, select = -c(Age.0,Age.5_1, Unnamed..1,X2,X7) )
df_catch
df_catch=df_catch[df_catch$Year>=1996,]

C=c( "#a1ddff","#70ccff", "#3fbaff", "#0ea9ff", "#008edc", "royalblue","#3333CC", "darkblue")

t=nrow(df_catch)
year=seq(1996,2022,length=t)
year
N=as.vector(data.matrix(subset(df_catch, select = -c(Year))))


df.age.str <- data.frame(group=as.factor(rep(1, 8*t)), year=rep(year, 8),
                         Age=(rep(paste("",(c(1:8))), each=t)),
                         count=N)
df.age.str$ratio=with(df.age.str,count/ ave(count, year, FUN=sum) )


#ggplot(df.age.str,aes(x=year, y=count, group=Age, fill=Age)) +  geom_area(col="black",, linewidth=0.3)  +  labs(x = 'Year', y='Number of baltic grey seals') +scale_fill_manual(values=C,name='Age') +  theme_classic(base_size = 16)

ggplot(df.age.str,aes(x=year, y=ratio, group=Age, fill=Age)) +  geom_area(col="black",, linewidth=0.3)  +  labs(x = 'Year', y='Frequency of age') +scale_fill_manual(values=C,name='Age') +  theme_classic(base_size = 16) + ggtitle("Demographic composition of herring in Bothninan Sea")

```
```{r}
df_catch=read.csv("/home/milenava/Seals/Grey_seals/Data_for_code/Herring_catch_in_numbers_at_age_ICES_GoR.csv")
#df_catch= subset(df_catch, select = -c(Age.0,Age.5_1, Unnamed..1,X2,X7) )
df_catch
df_catch=df_catch[df_catch$Year>=1996,]

C=c( "#a1ddff","#70ccff", "#3fbaff", "deepskyblue", "#0ea9ff", "#008edc", "royalblue","#3333CC", "darkblue")

t=nrow(df_catch)
year=seq(1996,2022,length=t)
year
N=as.vector(data.matrix(subset(df_catch, select = -c(Year))))

df_catch

df.age.str <- data.frame(group=as.factor(rep(1, 9*t)), year=rep(year, 9),
                         Age=(rep(paste("",(c(1:9))), each=t)),
                         count=N)
df.age.str$ratio=with(df.age.str,count/ ave(count, year, FUN=sum) )


#ggplot(df.age.str,aes(x=year, y=count, group=Age, fill=Age)) +  geom_area(col="black",, linewidth=0.3)  +  labs(x = 'Year', y='Number of baltic grey seals') +scale_fill_manual(values=C,name='Age') +  theme_classic(base_size = 16)

ggplot(df.age.str,aes(x=year, y=ratio, group=Age, fill=Age)) +  geom_area(col="black",, linewidth=0.3)  +  labs(x = 'Year', y='Frequency of age') +scale_fill_manual(values=C,name='Age') +  theme_classic(base_size = 16) + ggtitle("Demographic composition of herring in Bothninan Sea")

```


```{r}
df_her=read.csv("/home/milenava/Seals/Grey_seals/Data_for_code/ICES_herring_SSB.csv")
df_her
df_her_melt=melt(df_her, id="X")
df_her_melt$Area=df_her_melt$variable
df_her_melt$value=as.numeric(df_her_melt$value)
df_her_melt
ggplot(df_her_melt)+geom_line(aes(x=X, y=value, col=Area))
```

```{r}

```


```{r}

plot(df_BB$Year, df_GoR$X5, ylim=c(18,46))
points(df_BB$Year, df_BS$X5, col="red")
points(df_BB$Year, df_BB$X5, col="blue")

plot(df_BB$Year, df_GoR$X6, ylim=c(18,46))
points(df_BB$Year, df_BS$X6, col="red")
points(df_BB$Year, df_BB$X6, col="blue")

plot(df_BB$Year, df_GoR$X7plus, ylim=c(18,60))
points(df_BB$Year, df_BS$X7plus, col="red")
points(df_BB$Year, df_BB$X7plus, col="blue")


plot(df_sprat$Year, df_sprat$X5)
```
```{r}

df_her=read.csv("/home/milenava/Seals/Grey_seals/Data_for_code/ICES_herring_SSB.csv")
df_her
df_her=df_her[1:nrow(df_BB),1:4]
colnames(df_her) <-c("Year", "BS", "BB", "GoR")

```


```{r}
library("zoo")
m_BS=mean(df_her$BS, na.rm=TRUE)
m_BB=mean(df_her$BB, na.rm=TRUE)
m_GoR=mean(df_her$GoR, na.rm=TRUE)


df_her$MW2=(df_BB$X2*m_BB+df_BS$X2*m_BS+df_GoR$X2*m_GoR)/(m_BB+m_BS+m_GoR)
df_her$MW5=(df_BB$X5*m_BB+df_BS$X5*m_BS+df_GoR$X5*m_GoR)/(m_BB+m_BS+m_GoR)
df_her$MW6=(df_BB$X6*m_BB+df_BS$X6*m_BS+df_GoR$X6*m_GoR)/(m_BB+m_BS+m_GoR)

df_her$MW7plus=(df_BB$X7plus*m_BB+df_BS$X7plus*m_BS+df_GoR$X7plus*m_GoR)/(m_BB+m_BS+m_GoR)
#df_her$MW6=(df_BB$X6*m_BB+df_BS$X6*m_BS+df_GoR$X6*m_GoR)/(m_BB+m_BS+m_GoR)

df_her$R2=rollmean(df_her$MW2,3, fill=NA, align="right")
df_her$R5=rollmean(df_her$MW5,3, fill=NA, align="right")
df_her$R6=rollmean(df_her$MW6,3, fill=NA, align="right")
df_her$R7plus=rollmean(df_her$MW7plus,3, fill=NA, align="right")

df_her$Her_5plus=(df_her$R5+df_her$R6+df_her$R7plus)/3
df_her$Her_5plus=(df_her$R5+df_her$R6+df_her$R7plus)/3
df_her$Her_5plus.noroll=(df_her$MW5+df_her$MW6+df_her$MW7plus)/3

df_sprat$R5plus=rollmean(df_sprat$X5plus,3, fill=NA, align="right")

F=df_her[7:27,][c("Year", "Her_5plus")]
F=rbind(F,c(2023 ,32))
F$Sprat_5plus=append(df_sprat$R5plus[7:27], 11.2)
F$H_blubber=(F$Her_5plus-mean(F$Her_5plus))/sd(F$Her_5plus)
H=F$H_blubber
length(H)
F$Her_5plus=F$Her_5plus/100
F$Her_5plus
#F$Her_5plus=(F$Her_5plus-mean(F$Her_5plus))/sd(F$Her_5plus)
#F$Sprat_5plus=(F$Sprat_5plus-mean(F$Sprat_5plus))/sd(F$Sprat_5plus)
H=F$H_blubber
H
path<-"/home/milenava/Seals/Grey_seals/Processed_data/"

write.csv(F,  paste(path,"Fish_MWA_3_years_roll.csv", sep=""))
length(F)


H=df_her[7:27,][c("Year", "Her_5plus.noroll", "MW5", "MW7plus")]
H
H=rbind(H,c(2023 ,34))
H$H_blubber=(H$Her_5plus.noroll-mean(H$Her_5plus.noroll))/sd(H$Her_5plus.noroll)
H=H$H_blubber
H
length(H)
F$Her_5plus=F$Her_5plus/100
F$Her_5plus
#F$Her_5plus=(F$Her_5plus-mean(F$Her_5plus))/sd(F$Her_5plus)
#F$Sprat_5plus=(F$Sprat_5plus-mean(F$Sprat_5plus))/sd(F$Sprat_5plus)
H=F$H_blubber
H$
plot(H$MW5, ylim=c(28,50))
points(H$MW7plus, col="red")
```

```{r}
f=seq(from=0, to=1, length=30)
a=10
b=0.5*a

plot(f,1/(1+exp(-a*f+b)), ylim=c(0,1))

a=10
b=(a-1)/a
plot(f,a*f^2/(1+a*b*f^2))
```

